name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v4
      - name: Set up JDK 21
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn clean install package --file pom.xml